# Generated by Django 6.1.1 on 2026-09-15 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day_of_week', 'start_time', 'id'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='schedule.building', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='schedule.classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='schedule.group', verbose_name='Учебная группа'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='schedule.subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='schedule.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week_type',
            field=models.CharField(choices=[('odd', 'Нечётная'), ('even', 'Чётная')], max_length=4, verbose_name='Тип недели'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
    ]
