--
-- PostgreSQL database dump
--

\restrict fLAJkn0LxCLRWAl5qHjGhiQVuUIOmprO8VoYhHUa9XMWuBfcnDIoswrANvzuhvU

-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: schedule_building; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_building (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    address character varying(255) NOT NULL
);


--
-- Name: schedule_building_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule_building ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_building_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_classroom; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_classroom (
    id bigint NOT NULL,
    number character varying(20) NOT NULL,
    building_id bigint NOT NULL
);


--
-- Name: schedule_classroom_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule_classroom ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_classroom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_group (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: schedule_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_lesson; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_lesson (
    id bigint NOT NULL,
    day_of_week smallint NOT NULL,
    week_type character varying(4) NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    classroom_id bigint NOT NULL,
    group_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    CONSTRAINT lesson_end_after_start CHECK ((end_time > start_time)),
    CONSTRAINT lesson_valid_day CHECK (((day_of_week >= 1) AND (day_of_week <= 7))),
    CONSTRAINT lesson_valid_week CHECK (((week_type)::text = ANY ((ARRAY['odd'::character varying, 'even'::character varying])::text[]))),
    CONSTRAINT schedule_lesson_day_of_week_check CHECK ((day_of_week >= 0))
);


--
-- Name: schedule_lesson_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule_lesson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_lesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_subject; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_subject (
    id bigint NOT NULL,
    name character varying(200) NOT NULL
);


--
-- Name: schedule_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule_subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_teacher; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_teacher (
    id bigint NOT NULL,
    full_name character varying(200) NOT NULL
);


--
-- Name: schedule_teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule_teacher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_userprofile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_userprofile (
    id bigint NOT NULL,
    group_id bigint,
    user_id integer NOT NULL,
    university_group character varying(150) NOT NULL,
    study_form character varying(20) NOT NULL
);


--
-- Name: schedule_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Корпус	7	add_building
26	Can change Корпус	7	change_building
27	Can delete Корпус	7	delete_building
28	Can view Корпус	7	view_building
29	Can add Учебная группа	9	add_group
30	Can change Учебная группа	9	change_group
31	Can delete Учебная группа	9	delete_group
32	Can view Учебная группа	9	view_group
33	Can add Дисциплина	11	add_subject
34	Can change Дисциплина	11	change_subject
35	Can delete Дисциплина	11	delete_subject
36	Can view Дисциплина	11	view_subject
37	Can add Преподаватель	12	add_teacher
38	Can change Преподаватель	12	change_teacher
39	Can delete Преподаватель	12	delete_teacher
40	Can view Преподаватель	12	view_teacher
41	Can add Аудитория	8	add_classroom
42	Can change Аудитория	8	change_classroom
43	Can delete Аудитория	8	delete_classroom
44	Can view Аудитория	8	view_classroom
45	Can add Занятие	10	add_lesson
46	Can change Занятие	10	change_lesson
47	Can delete Занятие	10	delete_lesson
48	Can view Занятие	10	view_lesson
49	Can add Профиль пользователя	13	add_userprofile
50	Can change Профиль пользователя	13	change_userprofile
51	Can delete Профиль пользователя	13	delete_userprofile
52	Can view Профиль пользователя	13	view_userprofile
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	schedule	building
8	schedule	classroom
9	schedule	group
10	schedule	lesson
11	schedule	subject
12	schedule	teacher
13	schedule	userprofile
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-15 17:11:56.637538+03
2	auth	0001_initial	2026-09-15 17:11:56.70302+03
3	admin	0001_initial	2026-09-15 17:11:56.721278+03
4	admin	0002_logentry_remove_auto_add	2026-09-15 17:11:56.726012+03
5	admin	0003_logentry_add_action_flag_choices	2026-09-15 17:11:56.731107+03
6	contenttypes	0002_remove_content_type_name	2026-09-15 17:11:56.742441+03
7	auth	0002_alter_permission_name_max_length	2026-09-15 17:11:56.747788+03
8	auth	0003_alter_user_email_max_length	2026-09-15 17:11:56.753173+03
9	auth	0004_alter_user_username_opts	2026-09-15 17:11:56.757594+03
10	auth	0005_alter_user_last_login_null	2026-09-15 17:11:56.762464+03
11	auth	0006_require_contenttypes_0002	2026-09-15 17:11:56.763195+03
12	auth	0007_alter_validators_add_error_messages	2026-09-15 17:11:56.768135+03
13	auth	0008_alter_user_username_max_length	2026-09-15 17:11:56.776042+03
14	auth	0009_alter_user_last_name_max_length	2026-09-15 17:11:56.781371+03
15	auth	0010_alter_group_name_max_length	2026-09-15 17:11:56.788384+03
16	auth	0011_update_proxy_permissions	2026-09-15 17:11:56.792842+03
17	auth	0012_alter_user_first_name_max_length	2026-09-15 17:11:56.799265+03
18	schedule	0001_initial	2026-09-15 17:11:56.866945+03
19	schedule	0002_alter_building_options_alter_classroom_options_and_more	2026-09-15 17:11:56.903316+03
20	sessions	0001_initial	2026-09-15 17:11:56.911362+03
21	schedule	0003_userprofile	2026-09-15 17:22:52.589456+03
22	schedule	0004_alter_userprofile_user	2026-09-15 17:39:47.415786+03
23	schedule	0005_userprofile_university_group_study_form	2026-09-17 16:12:50.0918+03
\.


--
-- Data for Name: schedule_building; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.schedule_building (id, name, address) FROM stdin;
1	Главный корпус	Ростов-на-Дону, ул. Большая Садовая, 69/47
2	Факультет менеджмента и предпринимательства	Ростов-на-Дону, пер. Островского, 62
3	Юридический факультет	Ростов-на-Дону, ул. Максима Горького, 166
4	Факультет лингвистики и журналистики	Ростов-на-Дону, ул. Тургеневская, 49
5	Финансово-экономический колледж	Ростов-на-Дону, пер. Доломановский, 53
\.


--
-- Data for Name: schedule_classroom; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.schedule_classroom (id, number, building_id) FROM stdin;
1	212	1
2	214	1
3	305	2
4	201	1
5	401	1
6	402	1
7	403	1
8	401	2
9	402	2
10	403	2
11	401	3
12	402	3
13	403	3
14	401	4
15	402	4
16	403	4
17	401	5
18	402	5
19	403	5
\.


--
-- Data for Name: schedule_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.schedule_group (id, name) FROM stdin;
1	ИСТ-311
2	ИСТ-312
3	ИСТ-211
4	ИСТ-212
5	ИБ-211
6	ИБ-311
7	ЭК-211
8	ЭК-311
9	МЕН-211
10	МЕН-311
11	ЮР-211
12	ЛИН-211
\.


--
-- Data for Name: schedule_lesson; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.schedule_lesson (id, day_of_week, week_type, start_time, end_time, classroom_id, group_id, subject_id, teacher_id) FROM stdin;
1	1	odd	09:00:00	10:30:00	1	1	1	1
2	1	odd	10:40:00	12:10:00	2	1	2	2
3	1	even	09:00:00	10:30:00	1	1	1	1
4	3	odd	09:00:00	10:30:00	1	2	1	1
5	3	even	10:40:00	12:10:00	1	1	2	2
12	2	odd	09:00:00	10:30:00	3	1	3	3
14	4	odd	09:00:00	10:30:00	3	1	3	3
15	5	odd	10:40:00	12:10:00	4	1	4	4
16	6	odd	09:00:00	10:30:00	2	1	2	2
17	2	even	09:00:00	10:30:00	4	1	4	4
18	4	even	10:40:00	12:10:00	3	1	3	3
19	5	even	09:00:00	10:30:00	1	1	1	1
20	1	odd	09:00:00	10:30:00	4	2	4	4
21	2	odd	13:00:00	14:30:00	3	2	3	3
22	4	odd	10:40:00	12:10:00	2	2	2	2
23	1	even	10:40:00	12:10:00	1	2	1	1
24	3	even	09:00:00	10:30:00	4	2	4	4
79	2	even	10:10:00	11:40:00	5	5	17	13
13	2	odd	10:40:00	12:10:00	3	1	4	4
26	1	odd	08:30:00	10:00:00	8	3	7	7
27	1	odd	10:10:00	11:40:00	8	3	8	8
28	2	odd	08:30:00	10:00:00	11	3	9	9
29	2	odd	10:10:00	11:40:00	11	3	10	10
30	3	odd	08:30:00	10:00:00	14	3	11	11
31	3	odd	10:10:00	11:40:00	14	3	12	12
32	4	odd	08:30:00	10:00:00	17	3	13	13
33	4	odd	10:10:00	11:40:00	17	3	14	14
34	5	odd	08:30:00	10:00:00	5	3	15	15
35	5	odd	10:10:00	11:40:00	5	3	16	16
36	1	even	08:30:00	10:00:00	11	3	8	8
37	1	even	10:10:00	11:40:00	11	3	9	9
38	2	even	08:30:00	10:00:00	14	3	10	10
39	2	even	10:10:00	11:40:00	14	3	11	11
40	3	even	08:30:00	10:00:00	17	3	12	12
41	3	even	10:10:00	11:40:00	17	3	13	13
42	4	even	08:30:00	10:00:00	5	3	14	14
43	4	even	10:10:00	11:40:00	5	3	15	15
44	5	even	08:30:00	10:00:00	8	3	16	16
45	5	even	10:10:00	11:40:00	8	3	17	5
46	1	odd	08:30:00	10:00:00	11	4	10	8
47	1	odd	10:10:00	11:40:00	11	4	11	9
48	2	odd	08:30:00	10:00:00	14	4	12	10
49	2	odd	10:10:00	11:40:00	14	4	13	11
50	3	odd	08:30:00	10:00:00	17	4	14	12
51	3	odd	10:10:00	11:40:00	17	4	15	13
52	4	odd	08:30:00	10:00:00	5	4	16	14
53	4	odd	10:10:00	11:40:00	5	4	17	15
54	5	odd	08:30:00	10:00:00	8	4	18	16
55	5	odd	10:10:00	11:40:00	8	4	5	5
56	1	even	08:30:00	10:00:00	14	4	11	9
57	1	even	10:10:00	11:40:00	14	4	12	10
58	2	even	08:30:00	10:00:00	17	4	13	11
59	2	even	10:10:00	11:40:00	17	4	14	12
60	3	even	08:30:00	10:00:00	5	4	15	13
61	3	even	10:10:00	11:40:00	5	4	16	14
62	4	even	08:30:00	10:00:00	8	4	17	15
63	4	even	10:10:00	11:40:00	8	4	18	16
64	5	even	08:30:00	10:00:00	11	4	5	5
65	5	even	10:10:00	11:40:00	11	4	6	6
66	1	odd	08:30:00	10:00:00	14	5	13	9
67	1	odd	10:10:00	11:40:00	14	5	14	10
68	2	odd	08:30:00	10:00:00	17	5	15	11
69	2	odd	10:10:00	11:40:00	17	5	16	12
70	3	odd	08:30:00	10:00:00	5	5	17	13
71	3	odd	10:10:00	11:40:00	5	5	18	14
72	4	odd	08:30:00	10:00:00	8	5	5	15
73	4	odd	10:10:00	11:40:00	8	5	6	16
74	5	odd	08:30:00	10:00:00	11	5	7	5
75	5	odd	10:10:00	11:40:00	11	5	8	6
76	1	even	08:30:00	10:00:00	17	5	14	10
77	1	even	10:10:00	11:40:00	17	5	15	11
78	2	even	08:30:00	10:00:00	5	5	16	12
80	3	even	08:30:00	10:00:00	8	5	18	14
81	3	even	10:10:00	11:40:00	8	5	5	15
82	4	even	08:30:00	10:00:00	11	5	6	16
83	4	even	10:10:00	11:40:00	11	5	7	5
84	5	even	08:30:00	10:00:00	14	5	8	6
85	5	even	10:10:00	11:40:00	14	5	9	7
86	1	odd	08:30:00	10:00:00	17	6	16	10
87	1	odd	10:10:00	11:40:00	17	6	17	11
88	2	odd	08:30:00	10:00:00	5	6	18	12
89	2	odd	10:10:00	11:40:00	5	6	5	13
90	3	odd	08:30:00	10:00:00	8	6	6	14
91	3	odd	10:10:00	11:40:00	8	6	7	15
92	4	odd	08:30:00	10:00:00	11	6	8	16
93	4	odd	10:10:00	11:40:00	11	6	9	5
94	5	odd	08:30:00	10:00:00	14	6	10	6
95	5	odd	10:10:00	11:40:00	14	6	11	7
96	1	even	08:30:00	10:00:00	5	6	17	11
97	1	even	10:10:00	11:40:00	5	6	18	12
98	2	even	08:30:00	10:00:00	8	6	5	13
99	2	even	10:10:00	11:40:00	8	6	6	14
100	3	even	08:30:00	10:00:00	11	6	7	15
101	3	even	10:10:00	11:40:00	11	6	8	16
102	4	even	08:30:00	10:00:00	14	6	9	5
103	4	even	10:10:00	11:40:00	14	6	10	6
104	5	even	08:30:00	10:00:00	17	6	11	7
105	5	even	10:10:00	11:40:00	17	6	12	8
106	1	odd	08:30:00	10:00:00	5	7	5	11
107	1	odd	10:10:00	11:40:00	5	7	6	12
108	2	odd	08:30:00	10:00:00	8	7	7	13
109	2	odd	10:10:00	11:40:00	8	7	8	14
110	3	odd	08:30:00	10:00:00	11	7	9	15
111	3	odd	10:10:00	11:40:00	11	7	10	16
112	4	odd	08:30:00	10:00:00	14	7	11	5
113	4	odd	10:10:00	11:40:00	14	7	12	6
114	5	odd	08:30:00	10:00:00	17	7	13	7
115	5	odd	10:10:00	11:40:00	17	7	14	8
116	1	even	08:30:00	10:00:00	8	7	6	12
117	1	even	10:10:00	11:40:00	8	7	7	13
118	2	even	08:30:00	10:00:00	11	7	8	14
119	2	even	10:10:00	11:40:00	11	7	9	15
120	3	even	08:30:00	10:00:00	14	7	10	16
121	3	even	10:10:00	11:40:00	14	7	11	5
122	4	even	08:30:00	10:00:00	17	7	12	6
123	4	even	10:10:00	11:40:00	17	7	13	7
124	5	even	08:30:00	10:00:00	5	7	14	8
125	5	even	10:10:00	11:40:00	5	7	15	9
126	1	odd	08:30:00	10:00:00	9	8	8	12
127	1	odd	10:10:00	11:40:00	9	8	9	13
128	2	odd	08:30:00	10:00:00	12	8	10	14
129	2	odd	10:10:00	11:40:00	12	8	11	15
130	3	odd	08:30:00	10:00:00	15	8	12	16
131	3	odd	10:10:00	11:40:00	15	8	13	5
132	4	odd	08:30:00	10:00:00	18	8	14	6
133	4	odd	10:10:00	11:40:00	18	8	15	7
134	5	odd	08:30:00	10:00:00	6	8	16	8
135	5	odd	10:10:00	11:40:00	6	8	17	9
136	1	even	08:30:00	10:00:00	12	8	9	13
137	1	even	10:10:00	11:40:00	12	8	10	14
138	2	even	08:30:00	10:00:00	15	8	11	15
139	2	even	10:10:00	11:40:00	15	8	12	16
140	3	even	08:30:00	10:00:00	18	8	13	5
141	3	even	10:10:00	11:40:00	18	8	14	6
142	4	even	08:30:00	10:00:00	6	8	15	7
143	4	even	10:10:00	11:40:00	6	8	16	8
144	5	even	08:30:00	10:00:00	9	8	17	9
145	5	even	10:10:00	11:40:00	9	8	18	10
146	1	odd	08:30:00	10:00:00	12	9	11	13
147	1	odd	10:10:00	11:40:00	12	9	12	14
148	2	odd	08:30:00	10:00:00	15	9	13	15
149	2	odd	10:10:00	11:40:00	15	9	14	16
150	3	odd	08:30:00	10:00:00	18	9	15	5
151	3	odd	10:10:00	11:40:00	18	9	16	6
152	4	odd	08:30:00	10:00:00	6	9	17	7
153	4	odd	10:10:00	11:40:00	6	9	18	8
154	5	odd	08:30:00	10:00:00	9	9	5	9
155	5	odd	10:10:00	11:40:00	9	9	6	10
156	1	even	08:30:00	10:00:00	15	9	12	14
157	1	even	10:10:00	11:40:00	15	9	13	15
158	2	even	08:30:00	10:00:00	18	9	14	16
159	2	even	10:10:00	11:40:00	18	9	15	5
160	3	even	08:30:00	10:00:00	6	9	16	6
161	3	even	10:10:00	11:40:00	6	9	17	7
162	4	even	08:30:00	10:00:00	9	9	18	8
163	4	even	10:10:00	11:40:00	9	9	5	9
164	5	even	08:30:00	10:00:00	12	9	6	10
165	5	even	10:10:00	11:40:00	12	9	7	11
166	1	odd	08:30:00	10:00:00	15	10	14	14
167	1	odd	10:10:00	11:40:00	15	10	15	15
168	2	odd	08:30:00	10:00:00	18	10	16	16
169	2	odd	10:10:00	11:40:00	18	10	17	5
170	3	odd	08:30:00	10:00:00	6	10	18	6
171	3	odd	10:10:00	11:40:00	6	10	5	7
172	4	odd	08:30:00	10:00:00	9	10	6	8
173	4	odd	10:10:00	11:40:00	9	10	7	9
174	5	odd	08:30:00	10:00:00	12	10	8	10
175	5	odd	10:10:00	11:40:00	12	10	9	11
176	1	even	08:30:00	10:00:00	18	10	15	15
177	1	even	10:10:00	11:40:00	18	10	16	16
178	2	even	08:30:00	10:00:00	6	10	17	5
179	2	even	10:10:00	11:40:00	6	10	18	6
180	3	even	08:30:00	10:00:00	9	10	5	7
181	3	even	10:10:00	11:40:00	9	10	6	8
182	4	even	08:30:00	10:00:00	12	10	7	9
183	4	even	10:10:00	11:40:00	12	10	8	10
184	5	even	08:30:00	10:00:00	15	10	9	11
185	5	even	10:10:00	11:40:00	15	10	10	12
186	1	odd	08:30:00	10:00:00	18	11	17	15
187	1	odd	10:10:00	11:40:00	18	11	18	16
188	2	odd	08:30:00	10:00:00	6	11	5	5
189	2	odd	10:10:00	11:40:00	6	11	6	6
190	3	odd	08:30:00	10:00:00	9	11	7	7
191	3	odd	10:10:00	11:40:00	9	11	8	8
192	4	odd	08:30:00	10:00:00	12	11	9	9
193	4	odd	10:10:00	11:40:00	12	11	10	10
194	5	odd	08:30:00	10:00:00	15	11	11	11
195	5	odd	10:10:00	11:40:00	15	11	12	12
196	1	even	08:30:00	10:00:00	6	11	18	16
197	1	even	10:10:00	11:40:00	6	11	5	5
198	2	even	08:30:00	10:00:00	9	11	6	6
199	2	even	10:10:00	11:40:00	9	11	7	7
200	3	even	08:30:00	10:00:00	12	11	8	8
201	3	even	10:10:00	11:40:00	12	11	9	9
202	4	even	08:30:00	10:00:00	15	11	10	10
203	4	even	10:10:00	11:40:00	15	11	11	11
204	5	even	08:30:00	10:00:00	18	11	12	12
205	5	even	10:10:00	11:40:00	18	11	13	13
206	1	odd	08:30:00	10:00:00	6	12	6	16
207	1	odd	10:10:00	11:40:00	6	12	7	5
208	2	odd	08:30:00	10:00:00	9	12	8	6
209	2	odd	10:10:00	11:40:00	9	12	9	7
210	3	odd	08:30:00	10:00:00	12	12	10	8
211	3	odd	10:10:00	11:40:00	12	12	11	9
212	4	odd	08:30:00	10:00:00	15	12	12	10
213	4	odd	10:10:00	11:40:00	15	12	13	11
214	5	odd	08:30:00	10:00:00	18	12	14	12
215	5	odd	10:10:00	11:40:00	18	12	15	13
216	1	even	08:30:00	10:00:00	9	12	7	5
217	1	even	10:10:00	11:40:00	9	12	8	6
218	2	even	08:30:00	10:00:00	12	12	9	7
219	2	even	10:10:00	11:40:00	12	12	10	8
220	3	even	08:30:00	10:00:00	15	12	11	9
221	3	even	10:10:00	11:40:00	15	12	12	10
222	4	even	08:30:00	10:00:00	18	12	13	11
223	4	even	10:10:00	11:40:00	18	12	14	12
224	5	even	08:30:00	10:00:00	6	12	15	13
225	5	even	10:10:00	11:40:00	6	12	16	14
\.


--
-- Data for Name: schedule_subject; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.schedule_subject (id, name) FROM stdin;
1	Базы данных
2	Программирование
3	Веб-разработка
4	Высшая математика
5	Алгоритмы и структуры данных
6	Операционные системы
7	Компьютерные сети
8	Информационная безопасность
9	Теория вероятностей
10	Статистика
11	Микроэкономика
12	Макроэкономика
13	Бухгалтерский учёт
14	Финансовый менеджмент
15	Гражданское право
16	Теория государства и права
17	Иностранный язык
18	Деловые коммуникации
\.


--
-- Data for Name: schedule_teacher; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.schedule_teacher (id, full_name) FROM stdin;
1	Долженко А.И.
2	Иванова Е.В.
3	Смирнов Д.А.
4	Кузнецова М.С.
5	Петров А.С.
6	Соколова Н.В.
7	Волков И.П.
8	Морозова О.А.
9	Новиков С.В.
10	Фёдорова Е.А.
11	Орлов М.Д.
12	Лебедева Т.С.
13	Васильев Р.Н.
14	Зайцева Л.П.
15	Белов К.А.
16	Павлова Ю.В.
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 7, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 23, true);


--
-- Name: schedule_building_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.schedule_building_id_seq', 5, true);


--
-- Name: schedule_classroom_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.schedule_classroom_id_seq', 19, true);


--
-- Name: schedule_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.schedule_group_id_seq', 12, true);


--
-- Name: schedule_lesson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.schedule_lesson_id_seq', 225, true);


--
-- Name: schedule_subject_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.schedule_subject_id_seq', 18, true);


--
-- Name: schedule_teacher_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.schedule_teacher_id_seq', 16, true);


--
-- Name: schedule_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.schedule_userprofile_id_seq', 7, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: schedule_building schedule_building_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_building
    ADD CONSTRAINT schedule_building_name_key UNIQUE (name);


--
-- Name: schedule_building schedule_building_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_building
    ADD CONSTRAINT schedule_building_pkey PRIMARY KEY (id);


--
-- Name: schedule_classroom schedule_classroom_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_classroom
    ADD CONSTRAINT schedule_classroom_pkey PRIMARY KEY (id);


--
-- Name: schedule_group schedule_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_group
    ADD CONSTRAINT schedule_group_name_key UNIQUE (name);


--
-- Name: schedule_group schedule_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_group
    ADD CONSTRAINT schedule_group_pkey PRIMARY KEY (id);


--
-- Name: schedule_lesson schedule_lesson_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_lesson
    ADD CONSTRAINT schedule_lesson_pkey PRIMARY KEY (id);


--
-- Name: schedule_subject schedule_subject_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_subject
    ADD CONSTRAINT schedule_subject_name_key UNIQUE (name);


--
-- Name: schedule_subject schedule_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_subject
    ADD CONSTRAINT schedule_subject_pkey PRIMARY KEY (id);


--
-- Name: schedule_teacher schedule_teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_teacher
    ADD CONSTRAINT schedule_teacher_pkey PRIMARY KEY (id);


--
-- Name: schedule_userprofile schedule_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_userprofile
    ADD CONSTRAINT schedule_userprofile_pkey PRIMARY KEY (id);


--
-- Name: schedule_userprofile schedule_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_userprofile
    ADD CONSTRAINT schedule_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: schedule_classroom unique_classroom_in_building; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_classroom
    ADD CONSTRAINT unique_classroom_in_building UNIQUE (building_id, number);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: schedule_building_name_685a5f78_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schedule_building_name_685a5f78_like ON public.schedule_building USING btree (name varchar_pattern_ops);


--
-- Name: schedule_classroom_building_id_cfae1782; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schedule_classroom_building_id_cfae1782 ON public.schedule_classroom USING btree (building_id);


--
-- Name: schedule_group_name_f962270c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schedule_group_name_f962270c_like ON public.schedule_group USING btree (name varchar_pattern_ops);


--
-- Name: schedule_lesson_classroom_id_7b9b42a6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schedule_lesson_classroom_id_7b9b42a6 ON public.schedule_lesson USING btree (classroom_id);


--
-- Name: schedule_lesson_group_id_90f65ef8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schedule_lesson_group_id_90f65ef8 ON public.schedule_lesson USING btree (group_id);


--
-- Name: schedule_lesson_subject_id_c94c832f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schedule_lesson_subject_id_c94c832f ON public.schedule_lesson USING btree (subject_id);


--
-- Name: schedule_lesson_teacher_id_1c27ae23; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schedule_lesson_teacher_id_1c27ae23 ON public.schedule_lesson USING btree (teacher_id);


--
-- Name: schedule_subject_name_b3a36c19_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schedule_subject_name_b3a36c19_like ON public.schedule_subject USING btree (name varchar_pattern_ops);


--
-- Name: schedule_userprofile_group_id_7f671081; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX schedule_userprofile_group_id_7f671081 ON public.schedule_userprofile USING btree (group_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_classroom schedule_classroom_building_id_cfae1782_fk_schedule_building_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_classroom
    ADD CONSTRAINT schedule_classroom_building_id_cfae1782_fk_schedule_building_id FOREIGN KEY (building_id) REFERENCES public.schedule_building(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_lesson schedule_lesson_classroom_id_7b9b42a6_fk_schedule_classroom_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_lesson
    ADD CONSTRAINT schedule_lesson_classroom_id_7b9b42a6_fk_schedule_classroom_id FOREIGN KEY (classroom_id) REFERENCES public.schedule_classroom(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_lesson schedule_lesson_group_id_90f65ef8_fk_schedule_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_lesson
    ADD CONSTRAINT schedule_lesson_group_id_90f65ef8_fk_schedule_group_id FOREIGN KEY (group_id) REFERENCES public.schedule_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_lesson schedule_lesson_subject_id_c94c832f_fk_schedule_subject_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_lesson
    ADD CONSTRAINT schedule_lesson_subject_id_c94c832f_fk_schedule_subject_id FOREIGN KEY (subject_id) REFERENCES public.schedule_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_lesson schedule_lesson_teacher_id_1c27ae23_fk_schedule_teacher_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_lesson
    ADD CONSTRAINT schedule_lesson_teacher_id_1c27ae23_fk_schedule_teacher_id FOREIGN KEY (teacher_id) REFERENCES public.schedule_teacher(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_userprofile schedule_userprofile_group_id_7f671081_fk_schedule_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_userprofile
    ADD CONSTRAINT schedule_userprofile_group_id_7f671081_fk_schedule_group_id FOREIGN KEY (group_id) REFERENCES public.schedule_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_userprofile schedule_userprofile_user_id_a72dd99c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_userprofile
    ADD CONSTRAINT schedule_userprofile_user_id_a72dd99c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict fLAJkn0LxCLRWAl5qHjGhiQVuUIOmprO8VoYhHUa9XMWuBfcnDIoswrANvzuhvU
